export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  RESUMES: {
    ANALYZE: '/resumes/analyze',
  },
  STUDENTS: {
    PROFILE: '/students/profile',
    SKILLS: '/students/skills',
    INTERESTS: '/students/interests',
    GET_BY_ID: (id) => `/students/${id}`,
  },
  CAREERS: {
    BASE: '/careers',
    BY_ID: (id) => `/careers/${id}`,
    SEARCH: '/careers/search',
    CATEGORIES: '/careers/categories',
    RECOMMENDATIONS: (studentId) => `/careers/recommendations/${studentId}`,
    COMPARE: '/careers/compare',
  },
  EDUCATION: {
    COLLEGES: '/education/colleges',
    COLLEGE_BY_ID: (id) => `/education/colleges/${id}`,
    COURSES: '/education/courses',
    COURSE_BY_ID: (id) => `/education/courses/${id}`,
    SEARCH: '/education/search',
    RECOMMENDATIONS: (studentId) => `/education/recommendations/${studentId}`,
  },
  JOBS: {
    BASE: '/jobs',
    BY_ID: (id) => `/jobs/${id}`,
    SEARCH: '/jobs/search',
    RECOMMENDATIONS: (studentId) => `/jobs/recommendations/${studentId}`,
    SAVE: (id) => `/jobs/${id}/save`,
    SAVED: '/jobs/saved',
    APPLY: (id) => `/jobs/${id}/apply`,
    APPLICATIONS: '/jobs/applications',
  },
  ASSESSMENTS: {
    BASE: '/assessments',
    BY_ID: (id) => `/assessments/${id}`,
    QUESTIONS: (id) => `/assessments/${id}/questions`,
    START: (id) => `/assessments/${id}/start`,
    SUBMIT: (id) => `/assessments/${id}/submit`,
    RESULTS: '/assessments/results',
  },
  AI: {
    ASK: '/ai/ask',
  },
  STUDY_PLANS: {
    BASE: '/study-plans',
    BY_ID: (id) => `/study-plans/${id}`,
    TASKS: (planId) => `/study-plans/${planId}/tasks`,
    TASK_BY_ID: (taskId) => `/study-plans/tasks/${taskId}`,
  },
  PROGRESS: {
    BASE: '/progress',
    INCREMENT_ASSESSMENT: '/progress/increment-assessment',
    INCREMENT_JOB: '/progress/increment-job',
    INCREMENT_STUDY_PLAN: '/progress/increment-study-plan',
  },
  COUNSELORS: {
    BASE: '/counselors',
    PROFILE: '/counselors/profile',
    APPOINTMENTS: '/counselors/appointments',
    STUDENT_APPOINTMENTS: (studentId) => `/counselors/appointments/student/${studentId}`,
    COUNSELOR_APPOINTMENTS: (counselorId) => `/counselors/appointments/counselor/${counselorId}`,
    APPOINTMENT_STATUS: (id) => `/counselors/appointments/${id}/status`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    MARK_READ: (id) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
  },
  ADMIN: {
    ANALYTICS: '/admin/analytics',
  },
};
